package telran.cars.api;

public enum ReturnCode {
	OK, CAR_ALREADY_EXISTS, NO_CAR, MODEL_ALREADY_EXISTS, NO_MODEL,
	OWNER_ALREADY_EXISTS, NO_OWNER, WRONG_PURCHASE_DATE, WRONG_PARAMETRE,
	WRONG_YEAR

}
